### ISSUE TITLE
Predictions

### ISSUE THREAD

**Issue by digs1998** [karan1210/Python-in-medical-feild-#1]
What is it predicting in the end I wasn't able to understand

**Comment by karan1210** [comment]
After the feeding training set to the DL layers prediction cell print the output.
In this algorithm you find the probability of each class for example,  in our case we predict two class **1. NORML & 2. COVID19.** So the output form is **[0.5000, 0.5000] that means** image which we upload to **predict is 50% Normal and 50% COVID19.**
